// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzWF__-uh-ZGHHZofUDSUhnHyZp-iAf0c',
    appId: '1:703464234069:web:6708c800c7283c4bc888dc',
    messagingSenderId: '703464234069',
    projectId: 'petcare-v2-22b4d',
    authDomain: 'petcare-v2-22b4d.firebaseapp.com',
    storageBucket: 'petcare-v2-22b4d.firebasestorage.app',
    measurementId: 'G-YJ3YP3VH92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqIRLddJUNeef_aiSvZSoTVQ6CLtaDUt0',
    appId: '1:703464234069:android:536acc9ddb666ba8c888dc',
    messagingSenderId: '703464234069',
    projectId: 'petcare-v2-22b4d',
    storageBucket: 'petcare-v2-22b4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChoZabBNQV13oo7VcbqpkhyFjgdIT37ro',
    appId: '1:703464234069:ios:cc173cf8af54b3dec888dc',
    messagingSenderId: '703464234069',
    projectId: 'petcare-v2-22b4d',
    storageBucket: 'petcare-v2-22b4d.firebasestorage.app',
    iosBundleId: 'com.example.petcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChoZabBNQV13oo7VcbqpkhyFjgdIT37ro',
    appId: '1:703464234069:ios:cc173cf8af54b3dec888dc',
    messagingSenderId: '703464234069',
    projectId: 'petcare-v2-22b4d',
    storageBucket: 'petcare-v2-22b4d.firebasestorage.app',
    iosBundleId: 'com.example.petcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzWF__-uh-ZGHHZofUDSUhnHyZp-iAf0c',
    appId: '1:703464234069:web:9eaca3dc33a20cc4c888dc',
    messagingSenderId: '703464234069',
    projectId: 'petcare-v2-22b4d',
    authDomain: 'petcare-v2-22b4d.firebaseapp.com',
    storageBucket: 'petcare-v2-22b4d.firebasestorage.app',
    measurementId: 'G-Z2PHBH98HD',
  );
}
